version: "3.8"

services:
  infracontainer:
    image: paultegelaar/talend74infra:20210107_1111-V7.4.1M6
    networks:
      - talend_network
    restart: unless-stopped
    ports:
      - 8040:8040
      - 9001:9001
      - 2181:2181
    environment:
      - SQL_SERVER_HOST=talend74tos.database.windows.net
      - SQL_SERVER_PORT=1433
      - SQL_SERVER_DBNAME=talend
      - SQL_SERVER_USER=talendsam
      - SQL_SERVER_PASSWORD=Hallo1234!!
      - TALEND_SAM_USER_PASSWORD=HeyHoLetsGO!
      - TALEND_ADMIN_USER_PASSWORD=WeAreGoingToIbiza    
      
  serviceruntime01:
    image: paultegelaar/devtalend-service-runtime:0.0.1-SNAPSHOT
    depends_on:
      - infracontainer
    networks:
      - talend_network
    restart: unless-stopped
    ports:
      - 8041:8041
      - 9002:9002
      - 8102:8102
    environment:
      - LOCATOR_HOST=infracontainer
      - EXTERNAL_ADDRESS=serviceruntime01
      - SAM_HOST=infracontainer
      - TALEND_SAM_USER_PASSWORD=HeyHoLetsGO!
      - TALEND_ADMIN_USER_PASSWORD=WeAreGoingToIbiza
      - START_DELAY=15
      - TALEND_ESB_HTTPS_PORT=9002
      - TALEND_ESB_HTTP_PORT=8041
               
networks:
  talend_network:
    driver: bridge