version: "3.8"

services:
  infracontainer:
    image: paultegelaar/talend74infra:20201015_1726-V7.4.1M3
    networks:
      - talend_network
    restart: unless-stopped
    ports:
      - 8040:8040
      - 9001:9001
      - 2181:2181
    environment:
      - SQL_SERVER_HOST=localhost
      - SQL_SERVER_PORT=1433
      - SQL_SERVER_DBNAME=talendsam
      - SQL_SERVER_USER=talendsam
      - SQL_SERVER_PASSWORD=talendsam1234
      - TALEND_SAM_USER_PASSWORD=HeyHoLetsGO!
      - TALEND_ADMIN_USER_PASSWORD=WeAreGoingToIbiza
      
  processruntime01:
    image: paultegelaar/talend74runtime:20201015_1726-V7.4.1M3
    depends_on:
      - infracontainer
    networks:
      - talend_network
    restart: unless-stopped
    ports:
      - 8041:8041
      - 9002:9002
      - 8102:8102
    environment:
      - LOCATOR_HOST=infracontainer
      - EXTERNAL_ADDRESS=processruntime01
      - SAM_HOST=infracontainer
      - TALEND_SAM_USER_PASSWORD=HeyHoLetsGO!
      - TALEND_ADMIN_USER_PASSWORD=WeAreGoingToIbiza
      - CONTAINER_PORTS_SCRIPT=configureC1.sh
      
  serviceruntime01:
    image: paultegelaar/talend74runtime:20201015_1726-V7.4.1M3
    depends_on:
      - infracontainer
    networks:
      - talend_network
    restart: unless-stopped
    ports:
      - 8042:8042
      - 9003:9003
      - 8103:8103
    environment:
      - LOCATOR_HOST=infracontainer
      - EXTERNAL_ADDRESS=serviceruntime01
      - SAM_HOST=infracontainer
      - TALEND_SAM_USER_PASSWORD=HeyHoLetsGO!
      - TALEND_ADMIN_USER_PASSWORD=WeAreGoingToIbiza
      - CONTAINER_PORTS_SCRIPT=configureC2.sh
      
  apiruntime01:
    image: paultegelaar/talend74runtime:20201015_1726-V7.4.1M3
    depends_on:
      - infracontainer
    networks:
      - talend_network
    restart: unless-stopped
    ports:
      - 8043:8043
      - 9004:9004
      - 8104:8104
    environment:
      - LOCATOR_HOST=infracontainer
      - EXTERNAL_ADDRESS=sapiruntime01
      - SAM_HOST=infracontainer
      - TALEND_SAM_USER_PASSWORD=HeyHoLetsGO!
      - TALEND_ADMIN_USER_PASSWORD=WeAreGoingToIbiza
      - CONTAINER_PORTS_SCRIPT=configureC3.sh
     
networks:
  talend_network:
    driver: bridge